# -*- coding: utf-8 -*-
# $Id$

contest_time = 0
score_system = kirov
board_fog_time = 0
board_unfog_time = 0
standings_locale = "ru"

compile_dir = "../../compile/var/compile"

team_enable_src_view
team_enable_rep_view
team_enable_ce_view
team_show_judge_report
report_error_code
ignore_compile_errors
prune_empty_users
problem_navigation
vertical_navigation


max_run_size = 32K
max_run_num = 256


stand_fancy_style
stand_extra_format = "%UMp1s %UMp1f %UMp1g"

rounding_mode = floor
cr_serialization_key = 22723
show_astr_time
enable_runlog_merge
secure_run
detect_violations
enable_memory_limit_error
uuid_run_store
enable_l10n
team_download_time = 0
cpu_bogomips = 4800

[language]
id = 2
short_name = "gcc"
long_name = "GNU C 4.7.2"
src_sfx = ".c"

[language]
id = 3
short_name = "g++"
long_name = "GNU C++ 4.8.3"
src_sfx = ".cpp"

[problem]
abstract
short_name = "Generic"
use_stdin
use_stdout
test_dir = "%Ps"
test_sfx = ".dat"
use_corr
corr_dir = "%Ps"
corr_sfx = ".ans"
info_dir = "%Ps"
tgz_dir = "%Ps"
time_limit = 4
real_time_limit = 10
max_vm_size = 64M
max_stack_size = 64M
max_file_size = 64M
max_open_file_count = 32
max_process_count = 32
full_score = 1
check_cmd = "check_%Ps"
start_env = "EJUDGE_VG_FLAGS=-q --track-origins=yes --malloc-fill=66 --free-fill=66 --error-exitcode=1 --leak-check=full"
disable_user_submit = 0
disable_submit_after_ok = 0
enable_text_form

statement_file = "%Ps.html"

[problem]
abstract
short_name = "Generic_XML"
use_stdin
use_stdout
xml_file = "%Ps.xml"
test_dir = "%Ps"
test_sfx = ".dat"
use_corr
corr_dir = "%Ps"
corr_sfx = ".ans"
info_dir = "%Ps"
tgz_dir = "%Ps"
time_limit = 4
real_time_limit = 10
max_vm_size = 64M
max_stack_size = 64M
max_file_size = 64M
max_open_file_count = 32
max_process_count = 32
full_score = 1
check_cmd = "check_%Ps"
start_env = "EJUDGE_VG_FLAGS=-q --track-origins=yes --malloc-fill=66 --free-fill=66 --error-exitcode=1 --leak-check=full"
disable_user_submit = 0
disable_submit_after_ok = 0
enable_text_form

[problem]
abstract
short_name = "Generic_A"
type = "select-one"
xml_file = "%Ps.xml"
test_dir = "%Ps"
test_sfx = ".dat"
full_score = 1
run_penalty = 0
disqualified_penalty = 1
advance_to_next

[problem]
abstract
short_name = "Generic_B"
type = "short-answer"
use_stdin
use_stdout
xml_file = "%Ps.xml"
test_dir = "%Ps"
test_sfx = ".dat"
use_corr
corr_dir = "%Ps"
corr_sfx = ".ans"
time_limit = 1
real_time_limit = 1
full_score = 1
run_penalty = 0
disqualified_penalty = 1
check_cmd = "check_B"


[problem]
id = 40
super = "Generic_XML"
short_name = "func_fact"
long_name = "n!"
full_score = 30
standard_checker = "cmp_unsigned_long_long_seq"
valuer_cmd = ""
style_checker_cmd = "formatter"


[problem]
id = 50
super = "Generic"
short_name = "func_fib"
long_name = "fib"
full_score = 30
standard_checker = "cmp_unsigned_long_long_seq"
valuer_cmd = ""
source_header = "func_fib_begin.c"

[problem]
id = 60
super = "Generic_XML"
short_name = "deliteli"
long_name = ""
full_score = 40
standard_checker = "cmp_file"
source_header = "deliteli_begin.c"


[problem]
id = 70
super = "Generic"
short_name = "for_7"
long_name = "NOD NOK"
full_score = 40
standard_checker = "cmp_unsigned_long_long_seq"
valuer_cmd = ""
style_checker_cmd = "formatter"

[problem]
id = 80
super = "Generic_XML"
short_name = "rusMult"
long_name = ""
full_score = 40
standard_checker = "cmp_int_seq"


[problem]
id = 90
super = "Generic_XML"
short_name = "rusDel"
long_name = ""
full_score = 50
standard_checker = "cmp_file"


[problem]
id = 100
super = "Generic_XML"
short_name = "rusDelRem"
long_name = ""
full_score = 60
standard_checker = "cmp_file"


[problem]
id = 110
super = "Generic_XML"
short_name = "diafant"
long_name = "diafant"
full_score = 60
standard_checker = "cmp_file"





[tester]
name = Generic
arch = ""
abstract
no_core_dump
enable_memory_limit_error
kill_signal = KILL
memory_limit_type = "default"
secure_exec_type = "static"
clear_env
start_env = "PATH=/usr/local/bin:/usr/bin:/bin"
start_env = "HOME"
check_dir = "work-disk/work"

[tester]
any
super = Generic

# audit: created 2019/09/27 20:32:10 1 (ejudge) 95.143.216.192
